# Generated by Django 5.0.3 on 2024-03-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_vehical',
        ),
        migrations.RemoveField(
            model_name='category',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
