# Generated by Django 5.0.3 on 2024-03-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_delete_add_vehical_remove_category_car_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='vehical_type',
            new_name='vehical_Type',
        ),
    ]
