# Generated by Django 5.0.3 on 2024-03-11 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_rename_vehical_type_category_vehical_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehical_number', models.CharField(max_length=200)),
                ('add_area_no', models.CharField(max_length=200)),
                ('vehical', models.CharField(max_length=200)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('parked_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
