# Generated by Django 5.0.3 on 2024-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='activated', max_length=100),
        ),
        migrations.AlterField(
            model_name='add',
            name='status',
            field=models.CharField(choices=[('parked', 'parked'), ('leaved', 'leaved')], default='parked', max_length=10),
        ),
    ]
