# Generated by Django 5.0.3 on 2024-03-19 11:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area_no', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_limit', models.CharField(max_length=200)),
                ('parking_charge', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='activated', max_length=100)),
                ('doc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=11)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('parking_charge', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('parked', 'parked'), ('leaved', 'leaved')], default='parked', max_length=20)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
                ('parking_area_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.categoryentry')),
            ],
        ),
    ]
